lc = 0.01;
Point(1) = {0, 0, 0, lc};
Point(2) = {0.1, 0, 0, lc};
Point(3) = {0.1, 0.1, 0, lc};
Point(4) = {0, 0.1, 0, lc};
Line(1) = {1, 2};
Line(2) = {2, 3};
Line(3) = {3, 4};
Line(4) = {4, 1};
Line Loop(1) = {1, 2, 3, 4};
Plane Surface(1) = {1};
Physical Point("point") = {1};
Physical Line("down") = {1};
Physical Line("right") = {2};
Physical Line("up") = {3};
Physical Line("left") = {4};
Physical Surface("bottom") = {1};
Transfinite Line "*" = 3;
Transfinite Surface "*";
Recombine Surface "*";
